### ISSUE TITLE
Which tinyb version do you use?

### ISSUE THREAD

**Issue by HAKASHUN** [sputnikdev/bluetooth-manager-tinyb#2]
Hello, I'm looking at this very interesting project because I'm using [tinyb](https://github.com/intel-iot-devkit/tinyb/) on my project too.

Could you tell me the tinyb vesion (or commit) in this repository?

Best regards,
HAKASHUN

**Comment by vkolotov** [comment]
Hi @HAKASHUN , it is the most recent one: b5e293bb3c11abc21327f5c18d79436fab167038. Thanks.

**Comment by HAKASHUN** [comment]
Thank you for your reply.
I've understand.

**Comment by vkolotov** [comment]
If you are interested in the project, I suggest you to have a look at these projects as well:

https://github.com/sputnikdev/bluetooth-manager
and
https://github.com/sputnikdev/bluetooth-cli

@HAKASHUN  ^^
