### ISSUE TITLE
artifact is missing

### ISSUE THREAD

**Issue by jliang1010** [sputnikdev/bluetooth-manager-tinyb#8]
`[ERROR] Failed to execute goal on project bluetooth-manager-tinyb: Could not resolve dependencies for project org.sputnikdev:bluetooth-manager-tinyb:jar:1.3.2-SNAPSHOT: Could not find artifact intel-iot-devkit:tinyb:jar:0.6.0 in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots)`

Any idea? It was still ok 4 days ago. Couldn't find any declaration of related changes?

**Comment by vkolotov** [comment]
Hi @jliang1010, this is due to that TinyB library is not hosted in any maven repository, you have to install it in your local repo by yourself as per this: https://github.com/sputnikdev/bluetooth-manager-tinyb#building

```
sh .travis/install-dependencies.sh
```

**Comment by jliang1010** [comment]
@vkolotov thank you very much. I should have read through the document first :)
